apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: daemonset-otelcol
  namespace: opentelemetry
spec:
  image: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib"
  mode: daemonset
  hostNetwork: true
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        send_batch_size: 1000
        send_batch_max_size: 5000
        timeout: 5s
      
    exporters:
      debug:
        verbosity: detailed
      splunk_hec:
        token: "6e8749fe-1fcc-4bd6-aebd-762871effc72"
        endpoint: "https://192.168.1.102:8088/services/collector"
        tls:
          insecure_skip_verify: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug,splunk_hec]